/* TIM NHUNG CUON SACH DUOC CA DG01 va DG03 MUON */

SELECT S.ISBN
FROM SACH_CHITIET S JOIN MUONSACH MS ON S.ISBN = MS.ISBN JOIN TAIKHOAN TK ON TK.TENTK = MS.TENTK
WHERE TK.MADG = 'DG001'
UNION
SELECT S.ISBN
FROM hanoi.SACH_CHITIET@qltv_dblink S JOIN hanoi.MUONSACH@qltv_dblink MS ON S.ISBN = MS.ISBN JOIN hanoi.TAIKHOAN@qltv_dblink TK ON TK.TENTK = MS.TENTK
WHERE TK.MADG = 'DG003'
--------------------------------------------------------------------------------
/* TIM DOCGIA DA MUON TAT CA CAC LOAI SACH */

SELECT MADG, TENTK
FROM TAIKHOAN TK
WHERE NOT EXISTS(
                SELECT ISBN
                FROM SACH_CHITIET S
                WHERE NOT EXISTS(
                                SELECT ISBN, TENTK
                                FROM MUONSACH MS
                                WHERE MS.ISBN = S.ISBN AND MS.TENTK = TK.TENTK))
UNION
SELECT MADG, TENTK
FROM HANOI.TAIKHOAN@qltv_dblink TK
WHERE NOT EXISTS(
                SELECT ISBN
                FROM hanoi.SACH_CHITIET@qltv_dblink S
                WHERE NOT EXISTS(
                                SELECT ISBN, TENTK
                                FROM hanoi.MUONSACH@qltv_dblink MS
                                WHERE MS.ISBN = S.ISBN AND MS.TENTK = TK.TENTK))
--------------------------------------------------------------------------------
/* TINH TONG SOLUONG CUA TUNG CUON SACH DUOC MUON TRONG THANG 11/2021 */

SELECT S.ISBN, COUNT(MUONSACH.ISBN) AS SL
FROM SACH_CHITIET S, MUONSACH
WHERE S.ISBN=MUONSACH.ISBN AND EXTRACT(YEAR FROM MUONSACH.NGMUON) = 2021 
AND EXTRACT(MONTH FROM MUONSACH.NGMUON) = 11
GROUP BY S.ISBN
UNION
SELECT S.ISBN, COUNT(MUONSACH.ISBN) AS SL
FROM HANOI.SACH_CHITIET@QLTV_DBLINK S, HANOI.MUONSACH@QLTV_DBLINK
WHERE S.ISBN=MUONSACH.ISBN AND EXTRACT(YEAR FROM MUONSACH.NGMUON) = 2021 
AND EXTRACT(MONTH FROM MUONSACH.NGMUON) = 11
GROUP BY S.ISBN
ORDER BY SL DESC
--------------------------------------------------------------------------------
/* TINH CHI PHI TRUNG BINH KHI TRA SACH TRONG NAM 2021 */

SELECT AVG(CHIPHI) AS TB
FROM TRASACH
WHERE EXTRACT(YEAR FROM NGTRA) = 2021
UNION 
SELECT AVG(CHIPHI) AS TB
FROM HANOI.TRASACH@QLTV_DBLINK
WHERE EXTRACT(YEAR FROM NGTRA) = 2021
--------------------------------------------------------------------------------
/* TIM SACH DUOC VIP MUON NHIEU NHAT, VIP LA NHUNG DOCGIA MUON SACH TREN 5 LAN TAI 2 chi nhanh */

SELECT *
FROM
(
    SELECT ISBN, COUNT(ISBN) AS SL
    FROM MUONSACH
    WHERE MUONSACH.TENTK IN
    (
        SELECT TK.TENTK
        FROM TAIKHOAN TK ,MUONSACH MS
        WHERE TK.TENTK=MS.TENTK 
        GROUP BY TK.TENTK
        HAVING COUNT(TK.TENTK)>5
    )
    GROUP BY ISBN
    UNION
    SELECT ISBN, COUNT(ISBN) AS SL
    FROM hanoi.MUONSACH@qltv_dblink
    WHERE MUONSACH.TENTK IN
    (
        SELECT TK.TENTK
        FROM hanoi.TAIKHOAN@qltv_dblink TK ,hanoi.MUONSACH@qltv_dblink MS
        WHERE TK.TENTK=MS.TENTK 
        GROUP BY TK.TENTK
        HAVING COUNT(TK.TENTK)>5
    )
    GROUP BY ISBN
)
WHERE ROWNUM=1
ORDER BY SL DESC
--------------------------------------------------------------------------------
/*  TIM NHUNG CUON SACH KHONG DUOC MUON */
CREATE TABLE SACHBIM AS(
SELECT S.ISBN, TENSACH
FROM SACH_CHITIET S
WHERE NOT EXISTS(
                SELECT * FROM SACH_CHITIET S2, MUONSACH
                WHERE S2.ISBN = MUONSACH.ISBN
                AND S2.ISBN = S.ISBN));
INTERSECT
SELECT S.ISBN, TENSACH
FROM HANOI.SACH_CHITIET@qltv_dblink S
WHERE NOT EXISTS(
                SELECT * FROM hanoi.SACH_CHITIET@qltv_dblink S2, hanoi.MUONSACH@qltv_dblink
                WHERE S2.ISBN = MUONSACH.ISBN
                AND S2.ISBN = S.ISBN)

SELECT * FROM SACHBIM
UNION
SELECT * FROM HANOI.SACH_ANHDUCK@QLTV_DBLINK
--------------------------------------------------------------------------------
/*  TIM SOLUONG SACH KHAC NHAU DUOC MUON TRONG NAM 2021 */

SELECT COUNT(DISTINCT ISBN) as SOLUONG
FROM MUONSACH, TAIKHOAN
WHERE MUONSACH.TENTK = TAIKHOAN.TENTK
AND EXTRACT(YEAR FROM NGMUON) = 2021
UNION
SELECT COUNT(DISTINCT ISBN) AS SOLUONG
FROM HANOI.MUONSACH@qltv_dblink, hanoi.TAIKHOAN@qltv_dblink
WHERE MUONSACH.TENTK = TAIKHOAN.TENTK
AND EXTRACT(YEAR FROM NGMUON) = 2021
--------------------------------------------------------------------------------
/* IN RA TENTK, NGMUON, MAMS, ISBN MA KHONG CO KET QUA NAO TRUNG*/

SELECT TAIKHOAN.TENTK, NGMUON, MAMS,ISBN
FROM TAIKHOAN LEFT JOIN MUONSACH
ON TAIKHOAN.TENTK = MUONSACH.TENTK
UNION
SELECT TAIKHOAN.TENTK, NGMUON, MAMS,ISBN
FROM TAIKHOAN RIGHT JOIN MUONSACH
ON TAIKHOAN.TENTK = MUONSACH.TENTK
--------------------------------------------------------------------------------
/* IN RA ISBN, MADG, TENDG, TENSACH MA CHUA TRA SACH */

SELECT S.ISBN, DOCGIA.MADG, TENDG, S.TENSACH
FROM TAIKHOAN, DOCGIA, MUONSACH, SACH_CHITIET S
WHERE TAIKHOAN.MADG = DOCGIA.MADG
AND TAIKHOAN.TENTK = MUONSACH.TENTK
AND S.ISBN = MUONSACH.ISBN
AND MAMS NOT IN(
		SELECT MAMS
        FROM TRASACH);
UNION
SELECT S.ISBN, DOCGIA.MADG, TENDG, S.TENSACH
FROM hanoi.TAIKHOAN@qltv_dblink, hanoi.DOCGIA@qltv_dblink, hanoi.MUONSACH@qltv_dblink, hanoi.SACH_CHITIET@qltv_dblink S
WHERE TAIKHOAN.MADG = DOCGIA.MADG
AND TAIKHOAN.TENTK = MUONSACH.TENTK
AND S.ISBN = MUONSACH.ISBN
AND MAMS NOT IN(
		SELECT MAMS
        FROM hanoi.TRASACH@qltv_dblink)
--------------------------------------------------------------------------------
/* IN RA CUON SACH CO TRANG THAI LA UNAVAILABLE */

SELECT S1.ISBN, TENSACH
FROM SACH_CHITIET S1, SACH_SOLUOT S2
WHERE S1.ISBN = S2.ISBN
AND TINHTRANG = 'UNAVAILABLE'
UNION
SELECT S1.ISBN, TENSACH
FROM hanoi.SACH_CHITIET@qltv_dblink S1, hanoi.SACH_SOLUOT@qltv_dblink S2
WHERE S1.ISBN = S2.ISBN
AND TINHTRANG = 'UNAVAILABLE'